apiVersion: v1
kind: Service
metadata:
  name: pyflaskdockerapp-service
spec:
  selector:
    app: pyflaskdockerapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
